### PR TITLE
fix(frontend): Fix Jupyter tab overflow

### LINKED ISSUE #4714: [Bug]: if Jupyter Shell output has a long single line output, the UI container grows too wide and goes offscreen
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

To repro:
- Make the agent run a python script in the jupyter shell that outputs a really long line
- Hint, maybe have a raw file with a single extra  wide line and just ask the agent to read the file
- In the UI, switch to the Jupyter tab, notice the UI will grow extra wide and potentially go off screen

Switching between the workspace and the Jupyter tab will also somehow make the outer container of the right hand side of the UI grow wider and squeeze the left side conversation box narrower.

I think the fix should be along the lines of adding `wrapLongLines={true}` to the `Syntaxhighlighter` in the `Jupyter.tsx` file.
However, even after adding that, the width of the jupyter container will still grow wider when switching between the workspace tab and the jupyter tab.

### OpenHands Installation

Docker command in README

### OpenHands Version

_No response_

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by amanape**
**End-user friendly description of the problem this fixes or functionality that this introduces**
If there was a really long and single line input/output, it would stretch the container all the way and overflow!

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
- Introduce a hacky way to fix Jupyter to the parent width

There is actually a style mess with the containers and a few other hacky solutions have already been introduced (fix width of chat box, grow editor, and now fix juyter). This area should be revised soon BUT need careful consideration since we do want to implement resizable containers and is why I've not come to it yet.

Hopefully this week or next week I will introduce resizable containers and introduce proper containers

Screenshot 2024-11-07 at 15 30 09

---
**Link of any specific issues this addresses**
Resolves #4714

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:d345a98-nikolaik   --name openhands-app-d345a98   docker.all-hands.dev/all-hands-ai/openhands:d345a98
```

### CODE REVIEW

File: frontend/src/components/Jupyter.tsx [hunk 1]
```diff
@@ -88,9 +96,9 @@ function JupyterEditor(): JSX.Element {
     useScrollToBottom(jupyterRef);
 
   return (
-    <div className="flex-1">
+    <div className="flex-1 h-full w-full" style={{ maxWidth }}>
       <div
-        className="overflow-y-auto h-full"
+        className="overflow-auto h-full"
```
Comment (amanape) [inline frontend/src/components/Jupyter.tsx:101]:
```suggestion
        className="overflow-y-auto h-full"
```

File: frontend/src/components/Jupyter.tsx [hunk 2]
```diff
@@ -88,7 +96,7 @@ function JupyterEditor(): JSX.Element {
     useScrollToBottom(jupyterRef);
 
   return (
-    <div className="flex-1">
+    <div className="flex-1 h-full w-full" style={{ maxWidth }}>
```
Comment (amanape) [inline frontend/src/components/Jupyter.tsx:99]:
```suggestion
    <div className="flex-1" style={{ maxWidth }}>
```

**Review by enyst — APPROVED** [review]
Let's try.
