### PR TITLE
Runtime build fixes for OpenHands as a python library

### LINKED ISSUE #3571: [Bug]: Building runtime images fails with an opaque error when OpenHands is installed as a library
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When OpenHands is installed as a library, this line in `runtime_build.py` will fail, because the `pyproject.toml` file of OpenHands is not installed in the Python libraries directory (and it shouldn't be): https://github.com/All-Hands-AI/OpenHands/blob/36d1745b5e7efd46865160f3e34e6242fc5b828d/openhands/runtime/utils/runtime_build.py#L41

The resulting error is this:
```
07:00:30 - openhands:INFO: runtime_build.py:41 - Using project root: /Users/gneubig/miniconda3/envs/github-resolver/lib/python3.11/site-packages
ERROR Source /Users/gneubig/miniconda3/envs/github-resolver/lib/python3.11/site-packages does not appear to be a Python project: no pyproject.toml or setup.py
```

In order to fix this, we probably should just prevent building runtimes when OpenHands is installed as a library, and make the error more comprehensible, suggesting that the specify a runtime like ` ghcr.io/all-hands-ai/runtime:{VERSION_NO}`.

Or maybe we need some way to get the source distribution that corresponds to that version of OpenHands for use in that line above?

I'm not exactly sure the best method here so any feedback would be helpful (maybe cc @xingyaoww ?)

### Current OpenHands version

```bash
main
```

### Installation and Configuration

```bash
pip install openhands-ai
```

### Model and Agent

_No response_

### Operating System

_No response_

### Reproduction Steps

_No response_

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by li-boxuan**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

Make OpenHands usable as a python library, when a custom base image is used

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

This PR addresses the following issues:
1. Problem mentioned in #3571 (OpenHands cannot be used as a python library, if a custom sandbox image is needed)
2. "poetry.lock" is distributed at `site-packages` directory, which might conflict with other libraries:
image
3. `_put_source_code_to_dir` uses `build` library to create project tarball, which is too heavy.

I published a package using my branch: https://pypi.org/project/openhands-ai-test/ and was able to run OpenHands (using library) with a custom image.

---
**Link of any specific issues this addresses**

Fix #3571

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -0,0 +1,5 @@
+#!/bin/bash
+set -e
+
+cp pyproject.toml poetry.lock openhands
+poetry build
```
Comment (li-boxuan) [inline build.sh:5]:
```suggestion
poetry build -v
```

File: openhands/runtime/utils/runtime_build.py [hunk 2]
```diff
@@ -22,55 +21,49 @@ def get_runtime_image_repo():
...
-    shutil.unpack_archive(tarball_path, temp_dir)
-    # Remove the tarball
-    os.remove(tarball_path)
-    # Rename the directory containing the code to 'code'
-    os.rename(
-        os.path.join(temp_dir, f'openhands_ai-{package_version}'),
-        os.path.join(temp_dir, 'code'),
-    )
-    logger.info(f'Unpacked source code directory: {os.path.join(temp_dir, "code")}')
+    package_name = 'openhands-ai'
```
Comment (tobitege) [inline openhands/runtime/utils/runtime_build.py:30]: just a general question:
could it be beneficial to define such a value (and the 'openhands' literals) as global constants outside of this file so we don't have to hardcode it everywhere?

Comment (li-boxuan) [reply openhands/runtime/utils/runtime_build.py:30]: Yes 👍  will clean up before merging

File: pyproject.toml [hunk 3]
```diff
@@ -6,7 +6,6 @@ authors = ["OpenHands"]
 license = "MIT"
 readme = "README.md"
 repository = "https://github.com/All-Hands-AI/OpenHands"
-include = ["poetry.lock"]
```
Comment (xingyaoww) [inline pyproject.toml:9]: any idea why we want to remove this? - this will be helpfulto pin-down packages inside runtime though

File: openhands/runtime/utils/runtime_build.py [hunk 4]
```diff
@@ -22,55 +21,49 @@ def get_runtime_image_repo():
...
+    dest_dir = os.path.join(temp_dir, 'code')
+
+    try:
+        # Try to get the source directory from the installed package
+        distribution = importlib.metadata.distribution(package_name)
+        source_dir = os.path.dirname(distribution.locate_file(package_name))
+        openhands_dir = os.path.join(source_dir, 'openhands')
```
Comment (xingyaoww) [inline openhands/runtime/utils/runtime_build.py:37]: If this fails before, wouldn't `openhands_dir` be an undefined variable?

File: tests/unit/test_runtime_build.py [hunk 5]
```diff
@@ -54,15 +54,12 @@ def _check_source_code_in_dir(temp_dir):
     # check the source file is the same as the current code base
     assert os.path.exists(os.path.join(code_dir, 'pyproject.toml'))
 
-    # The source code should only include the `openhands` folder, but not the other folders
+    # The source code should only include the `openhands` folder,
+    # and pyproject.toml & poetry.lock that are needed to build the runtime image
     assert set(os.listdir(code_dir)) == {
-        'agenthub',
```
Comment (xingyaoww) [inline tests/unit/test_runtime_build.py:59]: any idea why we get rid of `agenthub`? would `openhands` package still able to function when that happens?

File: pyproject.toml (hunk 3 above)
Comment (li-boxuan) [reply pyproject.toml:9]: It cannot be included at root level. It's still used, but in my `build.sh`, it's copied to `openhands` directory.

Why not root level? It will pollute `site-packages` folder and might have conflicts with other libraries.

image

File: tests/unit/test_runtime_build.py (hunk 5 above)
Comment (li-boxuan) [reply tests/unit/test_runtime_build.py:59]: Yes it still functions. You can also import https://pypi.org/project/openhands-ai-test/ and run an agent to verify.

File: openhands/runtime/utils/runtime_build.py (hunk 4 above)
Comment (li-boxuan) [reply openhands/runtime/utils/runtime_build.py:37]: Will add a sanity check.

File: pyproject.toml (hunk 3 above)
Comment (li-boxuan) [reply pyproject.toml:9]: If you look at https://files.pythonhosted.org/packages/76/7c/f142053766542a3bf09a78de4e485246684d5da7a7fffc76f53eb1176565/openhands_ai_test-0.9.6.tar.gz,

you can see `openhands` directory now contains "poetry.lock" and "pyproject.toml".

File: openhands/runtime/utils/runtime_build.py (hunk 4 above)
Comment (xingyaoww) [reply openhands/runtime/utils/runtime_build.py:37]: Sounds good! I think once this sanity test is added, this PR should be ready to merge

Comment (li-boxuan) [reply openhands/runtime/utils/runtime_build.py:37]: I revisited this code and you are right that if the package doesn't exist (which happens when running from source code or packaged docker image), `openhands_dir` would be undefined.

The next code section would check if `openhands_dir` exists or not. If not, then it uses the current working directory as source (almost same as current behavior except it doesn't use the "build" system).

**Review by xingyaoww — APPROVED** [review]
LGTM - and it passes all tests :)
