### PR TITLE
Fix #5637: Check for errors in IPython content instead of message

### LINKED ISSUE #5637: [Bug]: Incorrectly interpreting a Python error as a success message
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

https://github.com/user-attachments/assets/2df6b5ae-6dbc-403c-a167-cd40c87c78f3

### OpenHands Installation

Docker command in README

### OpenHands Version

0.15.2, from `main`

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

The error message is
```
Parameter `old_str` is required for command: str_replace.
```

### PR DESCRIPTION
**Pull request by enyst**
This PR fixes #5637 with a simpler approach than PR #5644.

Instead of modifying the backend and adding extensive error detection, we simply check for errors in the content of the IPython output, which is where error messages appear.

The `message` property contains a static string, for an iPython obs; the `content` property should be filled with the actual content.

Changes:
- Modified `chat-slice.ts` to check `ipythonObs.content` instead of `ipythonObs.message` for error detection

This is a minimal change that addresses the core issue while keeping the codebase simpler.

### CODE REVIEW

File: frontend/src/state/chat-slice.ts [hunk 1]
```diff
@@ -148,7 +148,7 @@ export const chatSlice = createSlice({
       } else if (observationID === "run_ipython") {
         // For IPython, we consider it successful if there's no error message
         const ipythonObs = observation.payload as IPythonObservation;
-        causeMessage.success = !ipythonObs.message
+        causeMessage.success = !ipythonObs.content
           .toLowerCase()
           .includes("error");
```
Comment (enyst) [inline frontend/src/state/chat-slice.ts:153]:
```suggestion
          .includes("error:");
```

**Comment by enyst** [comment]
@neubig I won't be able to actually see this locally for some half a day. I do think this tweak is enough to fix the issue.

**Review by neubig — APPROVED** [review]
Thanks!
