### PR TITLE
hotfix(frontend): Clear base URL when advanced options is unselected

### LINKED ISSUE #4013: [Bug]: Base URL does not reset to empty after setting it once
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The Base URL does not get set to empty if you have set it once

### Current OpenHands version

```bash
main
```

### Installation and Configuration

```bash
make build
make run
```

### Model and Agent

N/A

### Operating System

MacOS

### Reproduction Steps

1. In the Settings UI, toggle Advanced Options and set Base URL to "https://test.com"
2. Set some random custom_model "openai/gpt-4o"
3. If you print the logs for Base URL (I have additional logging PR up which you can use when merged), you will see that base_url is set correctly
4. Now remove `Base URL` and press `Save`

You will see that Base URL is still set to "https://test.com" when it gets passed into the AgentSession (But appears empty in the UI)

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by amanape**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**
Clear the base URL when unselecting the advanced options switch

---
**TODO**
- [ ] ~~Fix set/unset bug:~~
  > Enable Advanced Options
  > Set Base URL
  > Remove Base URL

---
**Link of any specific issues this addresses**
Resolves #4013

### CODE REVIEW

**Comment by mamoodi** [comment]
Is it possible to fix the scenario where Advanced Options is still enabled but the Base URL was removed after setting it please?
* Enable Advanced Options
* Set Base URL
* Remove Base URL

**Review by neubig — APPROVED** [review]

File: frontend/src/components/modals/settings/SettingsForm.tsx [hunk 1]
```diff
@@ -52,13 +52,19 @@ function SettingsForm({
   const [enableAdvanced, setEnableAdvanced] =
     React.useState(advancedAlreadyInUse);
 
+  const handleAdvancedChange = (value: boolean) => {
+    setEnableAdvanced(value);
+    // Reset the base URL if the user disables advanced options
+    if (!value) onBaseURLChange("");
```
Comment (rbren) [inline frontend/src/components/modals/settings/SettingsForm.tsx:58]: Should we also clear security analyzer etc?

Comment (amanape) [reply frontend/src/components/modals/settings/SettingsForm.tsx:58]: That depends on what behaviour we want. What if the user is using a model we provide AND the security analyzer? If we clear when the advanced option is false, then we are only allowing the security analyzer, confirmation mode, etc... with custom models.

Right now the user can enable confirmation mode, switch to another model, and the mode is still enabled. We probably don't want the same behaviour for base URL though since that is (AFAIK) directly tied to the custom model, so it makes sense to clear it when advanced options are off.

IMO we should find better UI/UX for this, especially if settings will expand

Comment (enyst) [reply frontend/src/components/modals/settings/SettingsForm.tsx:58]: Just to note, we can use the Advanced Settings window for "standard" models too, not only custom models. It may be a little more to type, but I'm pretty sure it works.
