### PR TITLE
Fix chat input not clearing after image paste/drop

### LINKED ISSUE #5341: [Bug]: When an image is attached in the chat, the chat text is not cleared
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

In the chat, typically when you send a message, the message is cleared from the chat window. However, currently if you attach an image to the chat, the chat message is not cleared and remains in the chat window. See an example below.

Screenshot 2024-12-01 at 9 30 24 AM

It would be good if we could:
1. Write a test to reproduce the error
2. Fix the error

### OpenHands Installation

app.all-hands.dev

### OpenHands Version

_No response_

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by neubig**
Fixes #5341

When an image is attached to the chat (via paste or drag & drop), the chat text is not cleared. This PR fixes that by:

1. Adding tests to reproduce the issue
2. Modifying the `ChatInput` component to clear the text input when an image is pasted/dropped
3. Updating the `InteractiveChatBox` component to handle the controlled input state properly

[From @neubig, not OpenHands]

I have confirmed locally that this works as expected, in contrast to the screenshot in the issue.

Screenshot 2024-12-01 at 11 54 25 AM

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:209dac6-nikolaik   --name openhands-app-209dac6   docker.all-hands.dev/all-hands-ai/openhands:209dac6
```

### CODE REVIEW

File: frontend/src/components/chat-input.tsx [hunk 1]
```diff
@@ -51,6 +51,8 @@ export function ChatInput({
       if (files.length > 0) {
         event.preventDefault();
         onImagePaste(files);
+        // Clear the text input when an image is pasted
+        onChange?.("");
```
Comment (amanape) [inline frontend/src/components/chat-input.tsx:55]:
```suggestion
```

Avoid directly calling this function like this here. `ChatInput` is meant to allow the developer to define the behaviour through the `onChange` prop. In this case, the component that uses `ChatInput` (e.g., `InteractiveChatBox`) should define this behaviour.

File: frontend/src/components/chat-input.tsx [hunk 2]
```diff
@@ -77,14 +79,19 @@ export function ChatInput({
       );
       if (files.length > 0) {
         onImagePaste(files);
+        // Clear the text input when an image is dropped
+        onChange?.("");
```
Comment (amanape) [inline frontend/src/components/chat-input.tsx:83]:
```suggestion
```

File: frontend/src/components/chat-input.tsx [hunk 3]
```diff
@@ -77,14 +79,19 @@ export function ChatInput({
...
   const handleSubmitMessage = () => {
-    if (textareaRef.current?.value) {
-      onSubmit(textareaRef.current.value);
-      textareaRef.current.value = "";
+    if (value || (textareaRef.current?.value && !value)) {
+      onSubmit(value || textareaRef.current?.value || "");
+      if (!value && textareaRef.current) {
+        textareaRef.current.value = "";
+      }
+      onChange?.("");
```
Comment (amanape) [inline frontend/src/components/chat-input.tsx:94]:
```suggestion
    if (textareaRef.current?.value) {
      onSubmit(textareaRef.current.value);
      textareaRef.current.value = "";
```

Undo this change for similar reasons as for `onChange`

File: frontend/src/components/interactive-chat-box.tsx [hunk 4]
```diff
@@ -35,9 +35,21 @@ export function InteractiveChatBox({
     });
   };
 
+  const [inputValue, setInputValue] = React.useState(value || "");
+
+  React.useEffect(() => {
+    setInputValue(value || "");
+  }, [value]);
+
```
Comment (amanape) [inline frontend/src/components/interactive-chat-box.tsx:43]:
```suggestion
```

The props we accept should already handling the input state (`value` instead of `inputValue` and `onChange` instead of `setInputValue`)

File: frontend/__tests__/components/interactive-chat-box.test.tsx [hunk 5]
```diff
@@ -131,4 +131,71 @@ describe("InteractiveChatBox", () => {
...
+    clipboardEvent.clipboardData = {
+      files: [imageFile],
+      getData: () => "",
+    };
+
+    // Trigger paste event
+    fireEvent(textarea, clipboardEvent);
+
+    // The text input should be cleared
+    expect(textarea).toHaveValue("");
```
Comment (amanape) [inline frontend/__tests__/components/interactive-chat-box.test.tsx:164]:
```suggestion
```

Instead of directly asserting the textarea content, we can just keep the assertion that `onChange` has been with `""`, this will also indirectly test that the textarea content will be cleared (actually depending on the implementation of `onChange`). This will also make it easier to test the behaviour since we don't want to force the `ChatInput` to call `onChange` as done in below.

File: frontend/__tests__/components/interactive-chat-box.test.tsx [hunk 6]
```diff
@@ -131,4 +131,71 @@ describe("InteractiveChatBox", () => {
...
+      files: [imageFile],
+      types: ["Files"],
+    };
+    dropEvent.preventDefault = vi.fn();
+
+    // Trigger drop event
+    fireEvent(textarea, dropEvent);
+
+    // The text input should be cleared
+    expect(textarea).toHaveValue("");
```
Comment (amanape) [inline frontend/__tests__/components/interactive-chat-box.test.tsx:198]:
```suggestion
```

File: frontend/src/components/chat-input.tsx
Comment (amanape) [inline frontend/src/components/chat-input.tsx:1]: It is not necessary to make changes to this file in order to implement the new behaviour.

File: frontend/src/components/interactive-chat-box.tsx
Comment (amanape) [inline frontend/src/components/interactive-chat-box.tsx:1]: We do not require to add extra state to manage the input as we already manage it through the props passed. We can undo these changes and instead update https://github.com/All-Hands-AI/OpenHands/blob/b9b6cfd406814f453a1cfe46842cd7a7126b957b/frontend/src/components/features/chat/interactive-chat-box.tsx#L26-L28 to

```ts
  const handleUpload = (files: File[]) => {
    setImages((prevImages) => [...prevImages, ...files]);
    onChange?.("");
  };
```

**Review by amanape — CHANGES_REQUESTED** [review]
Thanks for adding the test! We can simplify the implementation and the test should pass.

Do we want to implement this behaviour though? I understand clearing the input and image after submission but clearing after uploading an image seems like a regression.

What if the user is typing their query, then pastes some images before submitting?

Once the changes are resolved I can merge conflicts.

**Comment by neubig** [comment]
@openhands-agent please:
1. Make all of the changes that amanape requested
2. Fix all merge errors with main
3. Check the files for the "Lint / Lint frontend" and "Run Frontend Unit Tests / FE Unit Tests" workflows, run the commands in these workflows, and make sure they pass

**Comment by malhotra5** [comment]
Made the following changes based on review feedback:

1. Removed the direct input clearing from `chat-input.tsx` as it was not necessary
2. Modified `interactive-chat-box.tsx` to:
   - Remove the local input state management (`inputValue` and `setInputValue`)
   - Pass the `value` and `onChange` props directly to `ChatInput`
   - Add `onChange?.("")` to the `handleUpload` function to clear the input when an image is uploaded
3. Updated the tests to focus on checking the `onChange` behavior rather than directly checking the textarea value

All lint checks and tests are passing. The code now maintains proper separation of concerns with `ChatInput` remaining a controlled component that delegates state management to its parent.

updates from openhands-agent

File: frontend/src/components/features/chat/chat-input.tsx
Comment (amanape) [inline frontend/src/components/features/chat/chat-input.tsx:1]: We can still undo all these changes made to this file in favour of calling the change handler in `frontend/src/components/features/chat/interactive-chat-box.tsx`

File: frontend/src/components/features/chat/interactive-chat-box.tsx [hunk 7]
```diff
@@ -38,6 +39,7 @@ export function InteractiveChatBox({
   const handleSubmit = (message: string) => {
     onSubmit(message, images);
     setImages([]);
+    onChange?.("");
```
Comment (amanape) [inline frontend/src/components/features/chat/interactive-chat-box.tsx:42]: I don't think adding it here is a good idea. If I've added an image accidentally and removed it, all my text data is gone too

**Review by amanape — CHANGES_REQUESTED** [review]

**Review by amanape — APPROVED** [review]
