### PR TITLE
test(frontend): Settings logic and new API key UI

### LINKED ISSUE #5856: [Bug]: Language input is broken
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

1. Clear application data (or open in incognito) to simulate first time start
2. Open account settings
  image
3. Select any language and save
4. Notice that it is still an empty input
5. Select another different language
6. Notice that the selected language is the previous language and not the latest selection

This reflects on the actual translations too. If I first select Deutsch, I see the default (English) translations. If I then select Norsk, I see the German translations instead of Norwegian

### OpenHands Installation

Docker command in README

### OpenHands Version

0.17

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by amanape**
**End-user friendly description of the problem this fixes or functionality that this introduces**
- Remove settings context in favor of the `useSettings` query hook and `useSaveSettings` mutation fn
- Move "are settings updated" logic to a provider
- Add basic e2e tests for settings
- Improve api key UI

Screenshot 2024-12-30 at 7 12 12 PM
Screenshot 2024-12-30 at 7 12 03 PM
Screenshot 2024-12-30 at 7 11 59 PM

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

---
**Link of any specific issues this addresses**
Resolves #5856 #5921

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:6b03fa3-nikolaik   --name openhands-app-6b03fa3   docker.all-hands.dev/all-hands-ai/openhands:6b03fa3
```

### CODE REVIEW

File: frontend/src/services/settings.ts [hunk 1]
```diff
@@ -115,34 +92,9 @@ export const maybeMigrateSettings = async (logout: () => void) => {
   if (currentVersion < 4) {
     logout();
   }
-
-  if (currentVersion < 5) {
-    const localSettings = getLocalStorageSettings();
-    await saveSettings(localSettings);
-  }
```
Comment (rbren) [inline frontend/src/services/settings.ts:122]: why did we lose this migration?

File: frontend/src/context/settings-up-to-date-context.tsx [hunk 2]
```diff
@@ -0,0 +1,42 @@
+import React from "react";
```
Comment (rbren) [inline frontend/src/context/settings-up-to-date-context.tsx:1]: this seems really heavy for checking that settings are up-to-date. Is there a better way?

Comment (rbren) [reply frontend/src/context/settings-up-to-date-context.tsx:1]: This "context" needs to get loaded for the entire application every time, so maybe we just put this logic into the base component?

File: frontend/src/services/settings.ts (hunk 1 above)
Comment (amanape) [reply frontend/src/services/settings.ts:122]: My mistake, I misread it as something else. I have since moved the settings migration logic to its own hook because it was utilizing some methods provided by other hooks.

I have also moved the logic away from being executed after saving settings to avoid complication (since the function needs to call save settings, the alternative solution was POST save settings -> migrate -> POST save settings again)

File: frontend/src/context/settings-up-to-date-context.tsx (hunk 2 above)
Comment (amanape) [reply frontend/src/context/settings-up-to-date-context.tsx:1]: This was my last option but the problem is we are fetching data from local storage. That means the functions to check whether it is up to date will only re-render if the component does, and in this case our sidebar does not re-render after a settings save mutation. For that reason I had to implement a context to properly manage the state

I think moving the logic into the base component would then require us to drill the set state action through a few prop/hooks, so better move it into a shared context to keep things simple

Comment (rbren) [reply frontend/src/context/settings-up-to-date-context.tsx:1]: OK--I think we can delete all this once everyone has transitioned

**Review by rbren — APPROVED** [review]
Does this fix the issue where we don't prompt for settings initially?

**Comment by amanape** [comment]
I wasn't able to replicate the issue since I can't seem to find `settings.json`. What I have done though is have the modal open if the GET settings returns an error off any kind
