### PR TITLE
Fix Push & Create PR button prompt to request meaningful branch names

### LINKED ISSUE #7527: [Bug]: Push and Create PR button is miswired and causing incorrect branch naming
**Describe the bug and reproduction steps**
The "Push and Create PR" button seems to be miswired and is causing unexpected behavior. When used, it pushes to a branch named `openhands-workspace-foo` rather than creating a meaningful branch name. Additionally, the prompt used appears to be mismatched with "Push to Branch" instead of the expected behavior for "Push and Create PR." This leads to the mishandling of branch names and workflow disruption.

**Potential solutions**
Robert mentioned that the prompt from "Push to Branch" got misused here. A closer look at the logic for determining and setting branch names might resolve this issue. Beyond that, re-aligning or verifying the functionality for the "Push and Create PR" workflow may help resolve this bug.

**Logs, Errors, Screenshots, and Additional Context**
Screenshot

**Issue Created By**: Xingyao Wang on Slack
**Link to Slack Thread**: https://openhands-ai.slack.com/archives/C078L0FUGUX/p1742947162100389?thread_ts=1742947162.100389&cid=C078L0FUGUX

### PR DESCRIPTION
**Pull request by xingyaoww**
This PR fixes issue #7527 by updating the prompt for the "Push & Create PR" button to request a meaningful branch name instead of using the same branch name.

The issue was that the "Push & Create PR" button was using the same prompt as the "Push to Branch" button, which was causing the branch to be named `openhands-workspace-foo` instead of a meaningful branch name.

Changes made:
1. Updated the prompt for the "Push & Create PR" button to request a meaningful branch name
2. Added tests to verify that the prompts are different

Fixes #7527

@xingyaoww can click here to [continue refining the PR](https://app.all-hands.dev/conversations/7bf1d5f4e7bb44b5adee650a69975465)

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:6d40e42-nikolaik   --name openhands-app-6d40e42   docker.all-hands.dev/all-hands-ai/openhands:6d40e42
```

### CODE REVIEW

File: frontend/src/components/features/chat/action-suggestions.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ export function ActionSuggestions({
                 suggestion={{
                   label: "Push & Create PR",
                   value:
-                    "Please push the changes to GitHub and open a pull request. Please use the exact SAME branch name as the one you are currently on.",
+                    "Please push the changes to GitHub and open a pull request. Please create a meaningful branch name that describes the changes.",
```
Comment (enyst) [inline frontend/src/components/features/chat/action-suggestions.tsx:43]: Not related to this PR, but to the other PR: once the user says this, this remains in history, and the conversation may continue after the first PR is opened
