### PR TITLE
Fix automatic lowercasing of model names in LLM integration

### LINKED ISSUE #9223: [Bug][SambaNova][Integration] SambaNova model is camel cased. Current lower-case on model name causing model not found
### Is there an existing issue for the same bug? (If one exists, thumbs up or comment on the issue instead).

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

**Reproduction step:**

I'm self-hosting OpenHands on premise. I chose sambanova as LLM provider by using the default drop down menu. I then start a conversation. I got an error:

```
18:08:13 - openhands:ERROR: session.py:332 - Agent status error: NotFoundError: litellm.NotFoundError: NotFoundError: SambanovaException - Error code: 404 - {'error': 'Model not found'}
18:08:13 - OBSERVATION
[Agent Controller 4f0235fc0c444b00b5bcd4a87ced2cc5] AgentStateChangedObservation(content='', agent_state='error', reason="NotFoundError: litellm.NotFoundError: NotFoundError: SambanovaException - Error code: 404 - {'error': 'Model not found'}", observation=<ObservationType.AGENT_STATE_CHANGED: 'agent_state_changed'>)
```
I've tried different models provided by SambaNova Systems and got the same Model not found error.

**Triage**
1. [DeepWiki](https://deepwiki.com/search/where-is-sambanova-integrated_eb7e43ee-3129-4d31-8b47-b36d4bf2fdd0) shows litellm is the means of integration. I've installed litellm separately and I was able to use litellm to call Sambanova's Cloud API. So litellm itself is fine.
2. Later, I re-examine the setting tab, it automatically shows advance, with model name lower-cased. [DeepWiki](https://deepwiki.com/search/where-is-sambanova-integrated_eb7e43ee-3129-4d31-8b47-b36d4bf2fdd0) does pointed out such lower-case logic. Particularly openhands/llm/llm.py line 172.
Since our model name is camel cased, such logic will results in model not found

**Conclusion** 
The lower-case logic doesn't work for SambaNova's model name. 

Image
Image

### OpenHands Installation

Docker command in README

### OpenHands Version

0.44

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

I started OpenHands locally by pulling docker image

```
docker pull docker.all-hands.dev/all-hands-ai/runtime:0.44-nikolaik

docker run -it --rm --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.44-nikolaik \
    -e LOG_ALL_EVENTS=true \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/.openhands:/.openhands \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.44
```

### PR DESCRIPTION
**Pull request by neubig**
## Summary

This PR fixes issue #9223 by removing automatic lowercasing of model names when checking for reasoning effort support in OpenHands LLM integration.

## Problem

The current implementation automatically converts model names to lowercase when checking if they support reasoning effort, which breaks SambaNova's camel-cased model names like `Meta-Llama-3.1-8B-Instruct` and other providers that use camel case or mixed case naming conventions.

## Solution

- **Removed `.lower()` calls** in 3 LLM classes when checking `REASONING_EFFORT_SUPPORTED_MODELS`:
  - `openhands/llm/llm.py` (line 172)
  - `openhands/llm/async_llm.py` (line 66) 
  - `openhands/llm/streaming_llm.py` (line 68)

- **Preserved case-sensitive matching** for exact model name comparisons
- **Left appropriate lowercasing intact** in `llm_utils.py` for substring checks (e.g., "gemini" provider detection)

## Testing

Added comprehensive test coverage for all 3 LLM classes:
- `test_model_name_case_sensitivity_for_reasoning_effort()` in `test_llm.py`
- `test_async_llm_model_name_case_sensitivity_for_reasoning_effort()` in `test_acompletion.py`
- `test_streaming_llm_model_name_case_sensitivity_for_reasoning_effort()` in `test_acompletion.py`

Tests verify:
- ✅ Lowercase models (`o1`, `o3-mini`) still get reasoning effort
- ✅ Camel case models (`CamelCaseModel`, `SambaNova-Model-Name`) do NOT get reasoning effort
- ✅ Provider/model split logic works correctly for slash-separated names
- ✅ Temperature removal works correctly for reasoning models

## Impact

This change ensures that:
- SambaNova and other providers with camel-cased model names work correctly
- Existing lowercase model names continue to work as expected
- No breaking changes to the API or configuration

Fixes #9223

@neubig can click here to [continue refining the PR](https://app.all-hands.dev/conversations/9ff5dc1cb22c4e0382bf4e9fce2b7210)

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:19e27c1-nikolaik   --name openhands-app-19e27c1   docker.all-hands.dev/all-hands-ai/openhands:19e27c1
```

### CODE REVIEW

File: frontend/src/utils/map-provider.ts [hunk 1]
```diff
@@ -29,3 +29,10 @@ export const mapProvider = (provider: string) =>
   Object.keys(MAP_PROVIDER).includes(provider)
     ? MAP_PROVIDER[provider as keyof typeof MAP_PROVIDER]
     : provider;
+
+export const unmapProvider = (displayName: string): string => {
```
Comment (xingyaoww) [inline frontend/src/utils/map-provider.ts]: nit: why are we calling it unmapProvider, seems a bit counter-intuitive -- this is maybe something like "getProviderName"?

**Comment by neubig** [comment]
@openhands change unmapProvider to getProviderId
