### PR TITLE
fix(frontend): Fix request headers

### LINKED ISSUE #4348: [Bug]: Feedback sending is broken in main
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Clicking the thumb down and confirming the popup causes the following red toast to appear:
`Failed to share, please contact the developers: TypeError: R.body is undefined`

In terminal also:
`INFO:     127.0.0.1:38594 - "POST /api/submit-feedback HTTP/1.1" 422 Unprocessable Entity`

### OpenHands Installation

Development workflow

### OpenHands Version

main

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by amanape**
**End-user friendly description of the problem this fixes or functionality that this introduces**
Requests were attempting to send JSON data without setting content-type, causing 422's in the server.

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
- Adds `"Content-Type": "application/json"` to the headers of requests that send JSON data

---
**Link of any specific issues this addresses**
Resolves #4348

### CODE REVIEW

**Review by rbren — APPROVED** [review]

File: frontend/src/api/open-hands.ts [hunk 1]
```diff
@@ -158,12 +170,14 @@ class OpenHands {
   static async sendFeedback(
     token: string,
     data: Feedback,
-    // TODO: Type the response
   ): Promise<FeedbackResponse> {
     const response = await fetch(`${OpenHands.BASE_URL}/api/submit-feedback`, {
       method: "POST",
-      headers: OpenHands.generateHeaders(token),
       body: JSON.stringify(data),
+      headers: {
```
Comment (rbren) [inline frontend/src/api/open-hands.ts:177]: Oh wait @amanape this has a different BASE_URL I believe

**Review by rbren — CHANGES_REQUESTED** [review]
need to fix the base url for share-feedback

File: frontend/src/api/open-hands.ts (hunk 1 above)
Comment (rbren) [reply frontend/src/api/open-hands.ts:177]: Nope I was wrong 🙃

**Review by rbren — APPROVED** [review]
