### PR TITLE
fix(frontend): Disable terminal stdin if the runtime is starting up

### LINKED ISSUE #5557: [Bug]: App breaks when running a command before runtime is active
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

1. Start new conversation
2. Run a command in the terminal as the runtime is initializing (e.g., `pwd`)
3. As soon as the runtime is supposed to be ready, we get a `There was an error while connecting to the runtime. Please refresh the page.`

Refreshing the page does **NOT** work. The Docker container is actually killed when the error is thrown

### OpenHands Installation

Docker command in README

### OpenHands Version

0.15.1

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

image

### PR DESCRIPTION
**Pull request by amanape**
**End-user friendly description of the problem this fixes or functionality that this introduces**
- User could submit commands before the runtime is active, causing a fatal error

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
- Disable stdin until the runtime is active
- A small indicator on the terminal label that shows whether the terminal is enabled or disabled (based on runtime status)
  Screenshot 2024-12-16 at 12 39 13

---
**Link of any specific issues this addresses**
Resolves #5557

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:2126a8e-nikolaik   --name openhands-app-2126a8e   docker.all-hands.dev/all-hands-ai/openhands:2126a8e
```

### CODE REVIEW

File: frontend/src/components/features/terminal/terminal.tsx [hunk 1]
```diff
@@ -1,16 +1,25 @@
...
 
 function Terminal({ secrets }: TerminalProps) {
+  const { status } = useWsClient();
   const { commands } = useSelector((state: RootState) => state.cmd);
-  const ref = useTerminal(commands, secrets);
+
+  const ref = useTerminal({
+    commands,
+    secrets,
+    disabled: status !== WsClientProviderStatus.ACTIVE,
```
Comment (enyst) [inline frontend/src/components/features/terminal/terminal.tsx:21]: Sorry, I'm a bit confused, doesn't this disable it when the websocket isn't active? That doesn't seem to be about the runtime at all

Comment (enyst) [reply frontend/src/components/features/terminal/terminal.tsx:21]: You may be right! My - probably silly - concern is about the opposite though: from the title of the PR/commit it sounds like it's tied to the state of the runtime, and IMHO that could disable _too much_?

Like, _during_ a session, the runtime can do some [strange stuff](https://openhands-ai.slack.com/archives/C07S376KASK/p1733028590467609), get errors, throw exceptions, or who knows, and currently it might be possible to restore it / reinit it, or even just chat with the LLM about its sad state. 😅

But the PR is not actually about the runtime? This enum can also be STOPPED or ERROR, not sure what are all cases when those get set, but as long as it's about the connection only, it's different IMHO - if you can't send, you can't send. Sorry, do I misunderstand?

Comment (amanape) [reply frontend/src/components/features/terminal/terminal.tsx:21]: Good points. I should revise the implementation (especially for the point about different enum values). Another thing I am seeing is that the only time the state is set to ACTIVE is on init event. I don't think this would work on a refresh since it doesn't look like we're getting another init event from the server on reloads.

Comment (amanape) [reply frontend/src/components/features/terminal/terminal.tsx]: Issue should be resolved. I've fixed the init event issue in #5632

**Review by enyst — APPROVED** [review]
Thanks!
